name: Deployment Count Report
on:
    workflow_call:
      inputs:
        repository_name:
          required: true
          type: string
        spreadsheet_id:
            required: true
            type: string
      secrets:
        DEPLOYMENT_REPORT_TOKEN:
            required: true
        GSHEET_CLIENT_EMAIL:
          required: true
        GSHEET_PRIVATE_KEY:
          required: true
jobs:
  get_deployments:
    name: Get Deployments
    outputs:
      total_deploy: ${{ steps.totalDeploy.outputs.totalNumber }}
      success_deploy: ${{ steps.successDeploy.outputs.successNumber }}
      other_deploy: ${{ steps.otherDeploy.outputs.otherNumber }}
      yesterday_date: ${{ steps.date.outputs.yesterdayDate }}
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "yesterdayDate=$(date --date='1 day ago' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Get Total Deployments JSON
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_REPORT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/zoocasa/${{ inputs.repository_name }}/actions/runs?event=push&created=${{ steps.date.outputs.yesterdayDate }}&branch=master" -o total.json
      - name: Get Total Deployments Number
        id: totalDeploy
        run: |
          echo "totalNumber=$(cat total.json | jq '.total_count')" >> $GITHUB_OUTPUT
      - name: Get Successful Deployments JSON
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_REPORT_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/zoocasa/${{ inputs.repository_name }}/actions/runs?event=push&created=${{ steps.date.outputs.yesterdayDate }}&branch=master&status=success" -o success.json
      - name: Get Total Deployments Number
        id: successDeploy
        run: |
          echo "successNumber=$(cat success.json | jq '.total_count')" >> $GITHUB_OUTPUT
      - name: Calculate Number of Unsuccessful Deployments
        id: otherDeploy
        run: |
          echo "otherNumber=$((${{ steps.totalDeploy.outputs.totalNumber }}-${{ steps.successDeploy.outputs.successNumber }}))" >> $GITHUB_OUTPUT
  deployment_report:
    name: Update Daily Deployments Google Sheet
    needs: get_deployments
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Write Deployment Counts
        id: update_worksheet
        uses: jroehl/gsheet.action@release
        with:
          spreadsheetId: ${{ inputs.spreadsheet_id }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "appendData", "args": { "data": [["${{ needs.get_deployments.outputs.yesterday_date }}", "${{ needs.get_deployments.outputs.total_deploy }}", "${{ needs.get_deployments.outputs.success_deploy }}", "${{ needs.get_deployments.outputs.other_deploy }}"]], "minCol": 1, "worksheetTitle": "Sheet1" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
