name: notion_ticket_updater

on:
  pull_request_target:
    branches:    
      - '**'  
    types: [opened, reopened, edited]
  workflow_call:

jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      BODY: "${{ github.event.pull_request.body }}"
      token: "${{ secrets.NOTION_SECRET_ACCESS_KEY }}"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Update Notion Ticket
        run: |
          ticketNumber="$(echo $BODY | grep -Eo "[?&]p=([^&#]*)" | head -1 | cut -c 4-)"
          number=${ticketNumber%% *}
          ticket=$(echo $number | tr -d '\r')
          var=$(curl --location --request GET "https://api.notion.com/v1/pages/$ticket" --header 'Notion-Version: 2022-06-28' --header "Authorization: Bearer $token"| jq -r .id) || exit
          
          echo $var
          
          curl --location --request PATCH "https://api.notion.com/v1/pages/${var}" \
          --header 'Notion-Version: 2022-06-28' \
          --header "Authorization: Bearer $token" \
          --header 'Content-Type: application/json' \
          --data-raw '{"properties": {"Status": {"select": {"name": "Code Review 🧑‍💻"}},"Git Branch": {"url": "${{github.event.pull_request.commits_url}}"},"Pull Request": {"url": "${{github.event.pull_request.url}}"}}}'
